### PR TITLE
Fix resolution of type identifiers

### LINKED ISSUE #51: LS: `goto` does not work for generic bounds
https://github.com/software-mansion/cairols/blob/d569db870dfd78b64b2b870c158c225cee78a3d6/tests/e2e/goto_definition/traits.rs#L270-L290

This also applies to trait/impl bounds

### LINKED ISSUE #405: Fix goto and rename on impl associated items
https://github.com/software-mansion/cairols/blob/30a27c5f5687723a2cde09ec4fb9c821cfb19aa8/tests/e2e/goto_definition/consts.rs#L56-L67

https://github.com/software-mansion/cairols/blob/30a27c5f5687723a2cde09ec4fb9c821cfb19aa8/tests/e2e/hover/consts.rs#L109-L129

https://github.com/software-mansion/cairols/blob/30a27c5f5687723a2cde09ec4fb9c821cfb19aa8/tests/e2e/find_references/consts.rs#L54-L65

https://github.com/software-mansion/cairols/blob/51acd3274fb7f33f5381a84c45ac8cb3e297c628/tests/e2e/rename/consts.rs#L55-L66

### LINKED ISSUE #435: Missing `usize` rename and references
### Problem

Tagged with `FIXME(#435)`
```cairo
#[derive(Drop)]
struct Foo { field: usi<caret>ze }
```
should also rename/find the `usize` at caret as reference

### Steps

_No response_

### Possible Solution(s)

_No response_

### Notes

_No response_

### Scarb Version

```text

```

### LINKED ISSUE #466: Invalid hover and goto on `u96` type
Hover for `u96` type in corelib's `circuit_test` contains the `BoundedInt`, which `u96` aliases, instead of the `u96` itself.
"Go to definition" also points to the original type, not to the definition of `u96`.

Image

same happens for impl aliases:

```cairo
// Pow implementation for any algebra.
impl AnyAlgebraPow<A, impl AlgImp: Algebra<A>> of Pow<A> { ... }

// Impl alias for Pow of i32.
impl Int32Pow = AnyAlgebraPow<i32, I32Algebra>;

// do goto definition on Int32Pow usage
```

### LINKED ISSUE #563: Implement hovers for associated items of traits and impls

### LINKED ISSUE #565: Implement hovers for trait bounds

### PR DESCRIPTION
**Pull request by integraledelebesgue**
Closes #51
Closes #405
Closes #435 
Closes #466
Closes #563
Closes #565

## Changes
* Type aliases are properly resolved to their definitions via `SymbolDef`
* LSP features work properly for type aliases and generic bounds, except for associated items in traits (#404)

### CODE REVIEW

**Comment by integraledelebesgue** [comment]
TODO: Impl aliases

File: src/lang/defs/finder.rs [hunk 1]
```diff
@@ -312,6 +327,71 @@ fn try_variable_declaration(
...
+            identifier.as_syntax_node().ancestor_of_type::<ast::ExprPath>(db)?.to_segments(db);
+
+        if type_path_segments
+            .last()
+            .is_none_or(|segment| segment.identifier(db) != identifier.text(db))
+        {
+            return None;
+        }
+
+        let mut resolver =
```
Comment (Arcticae) [inline src/lang/defs/finder.rs:366]: Shouldn't this be somehow derived from `resolver_data` (from calling function of `try_concrete_type` and passed down to `try_concrete_type`)?

File: src/lang/defs/finder.rs [hunk 2]
```diff
@@ -312,6 +327,71 @@ fn try_variable_declaration(
...
+        let resolved_generic = db.lookup_resolved_generic_item_by_ptr(lookup_item_id, ptr);
+
+        // If the type obviously resolves to an alias, return immedietely.
+        // This happens only in the `use` path.
+        if let Some(item @ ResolvedGenericItem::GenericTypeAlias(_)) = resolved_generic {
+            return Some(ResolvedItem::Generic(item));
+        }
+
+        // Compiler resolves the type aliases recursively, until it reaches a concrete type.
+        // If we calle [`SemanticGroup::resolve_concrete_item_by_ptr`],
```
Comment (Arcticae) [inline src/lang/defs/finder.rs:350]:
```suggestion
        // If we call [`SemanticGroup::resolve_concrete_item_by_ptr`],
```

**Review by Arcticae — APPROVED** [review]

**Review by piotmag769 — APPROVED** [review]
Uuu **resolver**
