### PR TITLE
Fix All imports

### LINKED ISSUE #229: Add "fix all imports" quick fix
### Problem

Like in other IDEs we should support fixing all of the import problems and suggesting many options in case of ambiguity in one of the places

### Proposed Solution

_No response_

### Notes

_No response_

### PR DESCRIPTION
**Pull request by Draggu**
close #229

### CODE REVIEW

File: src/ide/code_actions/mod.rs [hunk 1]
```diff
@@ -50,7 +51,9 @@ fn get_code_actions_for_diagnostics(
 ) -> Vec<CodeAction> {
     let uri = &params.text_document.uri;
 
-    params
+    let mut actions_for_fix_all = vec![];
```
Comment (piotmag769) [inline src/ide/code_actions/mod.rs:54]: Add missing trait here

**Review by Arcticae — APPROVED** [review]

**Review by piotmag769 — APPROVED** [review]
So you decided to collect all?

**Comment by Draggu** [comment]
> So you decided to collect all?

Now it is based on `is_preferred`, added where necessary in #390
