### PR TITLE
Fix semantic highlightning for attributes on `mod`s

### LINKED ISSUE #400: `cfg`s are not highlighted properly
### Problem

I have highlighting on `test` but not on `cfg`
Image

### Steps

_No response_

### Possible Solution(s)

_No response_

### Notes

_No response_

### Scarb Version

```text

```

### PR DESCRIPTION
**Pull request by Draggu**
Close #400

### CODE REVIEW

File: src/ide/semantic_highlighting/token_kind.rs [hunk 1]
```diff
@@ -22,6 +21,7 @@ pub enum SemanticTokenKind {
     Type,
     Parameter,
     Variable,
+    #[allow(dead_code)]
```
Comment (piotmag769) [inline src/ide/semantic_highlighting/token_kind.rs:24]: xD

File: src/ide/semantic_highlighting/token_kind.rs [hunk 2]
```diff
@@ -134,7 +134,7 @@ impl SemanticTokenKind {
                 _ => {}
             };
 
-            for lookup_item_id in db.collect_lookup_items_leaf(&node)? {
+            if let Some(lookup_item_id) = db.find_lookup_item(&node) {
```
Comment (piotmag769) [inline src/ide/semantic_highlighting/token_kind.rs:137]: No way XDDDDDD

File: tests/e2e/semantic_tokens/mod.rs [hunk 3]
```diff
@@ -1,38 +1,17 @@
-use lsp_types::lsp_request;
+use lsp_types::{Position, Range, lsp_request};
 
 use crate::support::cairo_project_toml::CAIRO_PROJECT_TOML_2023_11;
+use crate::support::cursor::render_text_with_annotations;
 use crate::support::sandbox;
+use cairo_language_server::testing::SemanticTokenKind;
 
-fn caps(base: lsp_types::ClientCapabilities) -> lsp_types::ClientCapabilities {
```
Comment (piotmag769) [inline tests/e2e/semantic_tokens/mod.rs:6]: [nit]: Would be nice if this was not moved (smaller diff), but w/e

**Review by piotmag769 — APPROVED** [review]

File: tests/e2e/semantic_tokens/mod.rs (hunk 3 above)
Comment (Draggu) [reply tests/e2e/semantic_tokens/mod.rs:6]: I did not expect this to be caught as rename by git.

**Review by integraledelebesgue — APPROVED** [review]
