### PR TITLE
Fix trait type `SymbolDef`

### LINKED ISSUE #170: Finding references and rename for impl methods does not traverse usages via trait
Tagged with `FIXME(#170)`

```cairo
#[derive(Drop)]
struct Foo {}

trait FooTrait {
    fn area(self: @Foo) -> u64;
}

impl FooImpl of FooTrait {
    fn are<caret>a(self: @Foo) -> u64 { 0 }
}

fn main() {
    let foo = Foo {};
    let x = foo.area();
}
```

This does not return `foo.<sel>area</sel>()`. It also should pick up `area` in `FooTrait` definition (to be discussed - would also affect goto).

Note that the expected outcome is to find all references to **this implementation method**. This means that if `FooTrait` would also be implemented for another struct, `Bar`, the usage `bar.area()` would not be picked up because it's not routed through `FooImpl`.

The same applies for alternative implementations of a same trait for same struct (say, `FooImplBis`).

Also when caret is on 

```cairo
trait FooTrait {
    fn a<caret>rea(self: @Foo) -> u64;
}
```

area inside `FooImpl` should be detected as definition/usage as well in this context.

### PR DESCRIPTION
**Pull request by Arcticae**
Closes #170 

- [x] Take impl impls themselves into account (their usage must be found properly when referred to - just like type in this PR)

### CODE REVIEW

**Review by Draggu — APPROVED** [review]

File: src/lang/db/semantic.rs [hunk 1]
```diff
@@ -324,6 +324,15 @@ fn lookup_item_from_ast(
...
         }
+        SyntaxKind::TraitItemType => {
+            vec![LookupItemId::TraitItem(TraitItemId::Type(
+                TraitTypeLongId(
+                    module_file_id,
+                    ast::TraitItemType::from_syntax_node(db, node).stable_ptr(db),
+                )
+                .intern(db),
+            ))]
+        }
```
Comment (piotmag769) [inline src/lang/db/semantic.rs:335]: This only changed fixed stuff in our find ref tests - do we not have tests for associated types for: rename, goto and highlight?

**Review by piotmag769 — APPROVED** [review]

File: tests/e2e/find_references/traits.rs [hunk 2]
```diff
@@ -392,6 +406,136 @@ fn dual_implementations_of_trait_via_trait_impl() {
...
+
+    impl GeorgeImpl of BushTrait {
+        impl BushImplementation = GeorgeBush;
+    }
+
+
+    fn main() {
+        let v1 = GeorgeImpl::BushImplemen<caret>tation::bush();
+        let v2 = GeorgeImpl::BushImplementation::bush();
+    }
```
Comment (piotmag769) [inline tests/e2e/find_references/traits.rs:440]: Add 
```cairo
impl KateImpl of BushTrait {
    impl BushImplementation = KateBush;
}

// main
KateBush::BushImplementation::bush();
```

**Review by piotmag769 — APPROVED** [review]
I think we need to review all tests at some point and make sure they cover everything

File: src/lang/db/semantic.rs (hunk 1 above)
Comment (Arcticae) [reply src/lang/db/semantic.rs:335]: https://github.com/software-mansion/cairols/issues/659

**Review by piotmag769 — APPROVED** [review]

**Review by integraledelebesgue — APPROVED** [review]
