### PR TITLE
Fix first segment `use` completions

### LINKED ISSUE #601: Fix first segment `use` completions
Currently `use core<caret>` won't propose anything. Appropriate tests should be added.

### PR DESCRIPTION
**Pull request by Draggu**
Close #601

### CODE REVIEW

File: tests/e2e/completions/module_items.rs [hunk 1]
```diff
@@ -142,3 +142,42 @@ fn non_existent_module() {
...
+    }
+
+    use helper_mod<caret>;
+    ",@r#"
+    caret = """
+    use helper_mod<caret>;
+    """
+
+    [[completions]]
+    completion_label = "hello"
```
Comment (Arcticae) [inline tests/e2e/completions/module_items.rs:167]: i don't understand the validity of this test tbh - why is it showing "hello"?

Comment (piotmag769) [reply tests/e2e/completions/module_items.rs:167]: I know how to fix it, will do

**Review by piotmag769 — APPROVED** [review]

File: src/ide/completion/use_statement.rs [hunk 2]
```diff
@@ -1,23 +1,68 @@
...
+    let importables =
+        db.visible_importables_from_module(ModuleFileId(ctx.module_id, FileIndex(0)))?;
+
+    Some(
+        importables
+            .iter()
+            .filter_map(|(importable, path)| {
+                match importable {
+                    // Other items can not be non-last segment, ignore them as it makes no sense to import them.
+                    ImportableId::Submodule(_) | ImportableId::Crate(_) | ImportableId::Enum(_)
```
[the remark this answers is not in the document]
Comment (piotmag769) [reply src/ide/completion/use_statement.rs:53]: Will be fixed when we merge https://github.com/starkware-libs/cairo/pull/7772 and bump cairo

**Review by piotmag769 — APPROVED** [review]

File: tests/e2e/completions/path.rs [hunk 3]
```diff
@@ -80,30 +80,6 @@ fn multi_segment_path() {
     "#);
 }
 
-#[test]
```
Comment (piotmag769) [inline tests/e2e/completions/path.rs:83]: Moved to `patterns`

File: tests/e2e/completions/patterns.rs [hunk 4]
```diff
@@ -195,3 +195,27 @@ fn partially_typed_nested() {
     completion_label = "abc"
     "#);
 }
+
+#[test]
```
Comment (piotmag769) [inline tests/e2e/completions/patterns.rs:199]: Moved from `path`, but git diff got confused

**Review by piotmag769 — APPROVED** [review]

**Review by integraledelebesgue — APPROVED** [review]
