### PR TITLE
Properly find definitions for variable declarations

### LINKED ISSUE #164: Goto definition does not work on pattern binding
Repro:

```cairo
fn foo() {
    let foo<caret>bar = 123;
}
```

```cairo
enum Foo {
    Bar,
}

fn foo() {
    let x = Foo::Bar;
    match x {
        Foo::Ba<caret>r => {},
    }
}
```

does not go to to this symbol.

### PR DESCRIPTION
**Pull request by mkaput**
fix #164
cc #129

---

**Stack**:
- #255
- #254
- #252
- #251
- #250
- #240 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Arcticae — APPROVED** [review]

File: src/lang/defs.rs [hunk 1]
```diff
@@ -462,41 +462,41 @@ fn find_definition(
...
-                }
-            }
-            LookupItemId::ImplItem(impl_item) => {
-                ResolvedGenericItem::Impl(impl_item.impl_def_id(db))
+    if let Some(var_id) = try_extract_variable_declaration(db, identifier, lookup_items) {
+        let item = ResolvedGenericItem::Variable(var_id);
+        return Some((ResolvedItem::Generic(item.clone()), resolved_generic_item_def(db, item)?));
+    }
+
+    // FIXME(mkaput): This logic always kicks in if we're finding definition of undefined symbol
```
Comment (Draggu) [inline src/lang/defs.rs:470]: issue/next PR ?

File: src/lang/defs.rs [hunk 2]
```diff
@@ -567,6 +567,56 @@ fn try_extract_member(
...
+
+        if let Some(param) =
+            params.into_iter().find(|param| param.stable_ptr == identifier.stable_ptr())
+        {
+            return Some(VarId::Param(param.id));
+        }
+    }
+
+    // Look at patterns in the function body.
+    if let Some(pattern) = identifier.as_syntax_node().parent_of_type::<ast::Pattern>(db) {
```
Comment (Draggu) [inline src/lang/defs.rs:606]: Won't it fail we are in different branch?
```
fn foo() {
    let bar = 123;
    let baz = ba<caret>r;
}
```

File: src/lang/defs.rs (hunk 1 above)
Comment (mkaput) [reply src/lang/defs.rs:470]: gonna be next PR

File: src/lang/defs.rs (hunk 2 above)
Comment (mkaput) [reply src/lang/defs.rs:606]: I don't understand, sorry. In your code snippet, `ba<caret>r` is an `ExprPath`, and there's no `Pattern` there.

**Review by Draggu — APPROVED** [review]

File: tests/e2e/hover/structs.rs [hunk 3]
```diff
@@ -248,9 +248,15 @@ fn non_existent_struct_member_init() {
...
+    highlight = """
+            let _ = NonExistentStruct { <sel>member</sel>: 0 };
+    """
     popover = """
     ```cairo
-    <missing>
+    hello::unhappy_cases
+    ```
+    ```cairo
+    fn non_existent_struct
```
Comment (piotmag769) [inline tests/e2e/hover/structs.rs:259]: This doesn't work no?

File: tests/e2e/hover/paths.rs [hunk 4]
```diff
@@ -502,9 +502,15 @@ fn struct_constructor_with_path_first() {
...
+    highlight = """
+            let _ = <sel>super</sel>::some_module::internal_module::nested_internal_module::PublicStruct {};
+    """
     popover = """
     ```cairo
-    hello::some_module::internal_module::nested_internal_module::PublicStruct
+    hello::happy_cases
+    ```
+    ```cairo
+    fn constructor_with_path()
```
Comment (piotmag769) [inline tests/e2e/hover/paths.rs:513]: This doesn't work no?

File: tests/e2e/hover/partial.rs [hunk 5]
```diff
@@ -25,9 +32,15 @@ fn uninfered_value() {
...
+    highlight = """
+        let mut xyz = <sel>unknown_function</sel>();
+    """
     popover = """
     ```cairo
-    <missing>
+    hello
+    ```
+    ```cairo
+    fn main()
```
Comment (piotmag769) [inline tests/e2e/hover/partial.rs:43]: Is that desired?
