### PR TITLE
Fix renames for traits 

### LINKED ISSUE #648: Fix behavior of `rename` with impl items
This should work differently than `find references` does - instead of renaming just usages of a specific impl - it should rename the trait as well, as other usages of other impls

(this is most likely what the user needs done, renaming just impl and usages won't make sense during the compilation after the rename - making it effectively invalid)

### PR DESCRIPTION
**Pull request by Arcticae**
closes #648

### CODE REVIEW

File: src/ide/navigation/rename.rs [hunk 1]
```diff
@@ -41,7 +41,7 @@ pub fn rename(
         let position = params.text_document_position.position.to_cairo();
         let identifier = db.find_identifier_at_position(file, position)?;
 
-        SymbolSearch::find_definition(db, &identifier).map(|search| search.def)
+        SymbolSearch::find_declaration(db, &identifier).map(|search| search.def)
```
Comment (piotmag769) [inline src/ide/navigation/rename.rs:44]: Please doc why

**Review by piotmag769 — APPROVED** [review]
